#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__bot_users() {
  existingUsers=$(yq -r '.bot_users|join(",")' "$install_dir/config.yaml")

  cat <<EOF
"$existingUsers"
EOF
}

get__admins() {
  existingAdmins=$(yq -r '.admins|join(",")' "$install_dir/config.yaml")

  cat <<EOF
"$existingAdmins"
EOF
}

get__bridge_instances() {
    value=$(ynh_app_setting_set --key=bridge_instances)
    choices=$(ls -d /etc/yunohost/apps/mautrix_*| sed s@/etc/yunohost/apps/@@ | tr '\n' ',')

echo "value: '$value'"
echo "choices:"
for bridge_instance in $(ls -d /etc/yunohost/apps/mautrix_*| sed s@/etc/yunohost/apps/@@)
   do
       echo "  - $bridge_instance"
   done
}

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__bridge_instances() {
  ynh_app_setting_set --key=bridge_instances --value="$bridge_instances"
  set_bridge_config_from_ids
  config="$install_dir/config.yaml"
  ynh_write_var_in_file --file="$config" --key="bot" --value="$botname_wa" --after="whatsapp"
  ynh_write_var_in_file --file="$config" --key="command" --value="$command_prefix_wa" --after="whatsapp"
  ynh_write_var_in_file --file="$config" --key="puppet" --value="$username_template_wa" --after="whatsapp"
  
  ynh_write_var_in_file --file="$config" --key="bot" --value="$botname_sg" --after="signal"
  ynh_write_var_in_file --file="$config" --key="command" --value="$command_prefix_sg" --after="signal"
  ynh_write_var_in_file --file="$config" --key="puppet" --value="$username_template_sg" --after="signal"
  
  ynh_write_var_in_file --file="$config" --key="bot" --value="$botname_tg" --after="telegram"
  ynh_write_var_in_file --file="$config" --key="command" --value="$command_prefix_tg" --after="telegram"
  ynh_write_var_in_file --file="$config" --key="puppet" --value="$username_template_tg" --after="telegram"
  
  ynh_store_file_checksum "$install_dir/config.yaml"
}

# !!!!!!!!!!!!!!!!!!!!!!!
# WARNING: there are custom setters into _common.sh
# !!!!!!!!!!!!!!!!!!!!!!!

ynh_app_config_run $1
