#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# Satisfy shellcheck, those variables are known when starting the script:
# shellcheck disable=SC2154
echo From manifest: "$homeserver", \
     From yunohost: "$app $install_dir" > /dev/null

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

synapse_install_dir=$(ynh_app_setting_get --app $homeserver --key install_dir)
server_name=$(ynh_app_setting_get --app $homeserver --key server_name)
domain=$(ynh_app_setting_get --app $homeserver --key domain)
port_synapse_tls=$(ynh_app_setting_get --app $homeserver --key port_synapse_tls)
device_id=$(ynh_string_random --filter='A-Z' --length=11)
device_name=$(ynh_string_random --filter='A-Z' --length=9)
ynh_app_setting_set --key=device_id --value=$device_id
ynh_app_setting_set --key=device_name --value=$device_name
ynh_app_setting_set --key=server_name --value=$server_name
ynh_app_setting_set --key=domain --value=$domain
ynh_app_setting_set --key=port_synapse_tls --value=$port_synapse_tls

#=================================================
# SET STANDARD SETTINGS FROM DEFAULT CONFIG
#=================================================

if [ "$botusers" == "domain.tld" ]; then
	bot_users="$server_name"
fi

if [ "$admins" == "@admin:domain.tld" ]; then
	admins="@admin:$server_name"
fi

relaybot_admin="@$botaccount:$server_name" 
welcome_message="ask_portal_admin"

ynh_app_setting_set --key=bot_users --value=$bot_users
ynh_app_setting_set --key=admins --value=$admins
ynh_app_setting_set --key=bridge_instances --value=$bridge_instances
ynh_app_setting_set --key=relaybot_admin --value=$relaybot_admin
ynh_app_setting_set --key=welcome_message --value=$welcome_message

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

# Install virtualenv
python3 -m venv $install_dir
export HOME=$install_dir
$install_dir/bin/pip3 install --upgrade pip setuptools wheel

if [ "$encryption" -eq "1" ];	then
	$install_dir/bin/pip3 install -r $install_dir/requirements_e2b.txt
else
	$install_dir/bin/pip3 install -r $install_dir/requirements.txt
fi

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

set_bridge_config_from_ids
ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

# This calls allows to set multiple users during install question "botusers" specifying them separated by a comma
set__bot_users
set__admins

chown -R "$app:$app" "$install_dir"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="Robot ARN-Messager" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service and pass password to get access_token
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
