#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# Satisfy shellcheck, those variables are known when starting the script:
# shellcheck disable=SC2154
echo From manifest: "$homeserver", \
     From yunohost: "$app $install_dir" > /dev/null

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

synapse_install_dir=$(ynh_app_setting_get --app $homeserver --key install_dir)
server_name=$(ynh_app_setting_get --app $homeserver --key server_name)
domain=$(ynh_app_setting_get --app $homeserver --key domain)
port_synapse_tls=$(ynh_app_setting_get --app $homeserver --key port_synapse_tls)
ynh_app_setting_set --key=server_name --value=$server_name
ynh_app_setting_set --key=domain --value=$domain
ynh_app_setting_set --key=port_synapse_tls --value=$port_synapse_tls


#=================================================
# SET STANDARD SETTINGS FROM DEFAULT CONFIG
#=================================================

#listuser=$(ynh_app_setting_get --app "$bridge" --key listuser)
#listadmin=$(ynh_app_setting_get --app "$bridge" --key listadmin)
if [ "$botusers" == "domain.tld" ]; then
	botusers="$server_name"
fi

if [ "$admins" == "@admin:domain.tld" ]; then
	admins="@admin:$server_name"
fi
listuser=$botusers
listadmin=$admins
#device_name="QSDGZETEZ"
im_bridged=$bridge
bot_name=$botname
bot_number=$botnumber
lang=$language

ynh_app_setting_set --key=botaccount --value=$botaccount
relaybot_admin="@$botaccount:$server_name" 
welcome_message="ask_portal_admin"

ynh_app_setting_set --key=listuser --value=$listuser
ynh_app_setting_set --key=listadmin --value=$listadmin
ynh_app_setting_set --key=im_bridged --value=$im_bridged
ynh_app_setting_set --key=bot_name --value=$bot_name
ynh_app_setting_set --key=bot_number --value=$bot_number
ynh_app_setting_set --key=lang --value=$lang
ynh_app_setting_set --key=welcome_message --value=$welcome_message

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

# Install virtualenv
python3 -m venv $install_dir

if $encryption;	then
	export HOME=$install_dir
	$install_dir/bin/pip3 install --upgrade pip setuptools wheel
	$install_dir/bin/pip3 install --upgrade python-olm matrix-nio[e2e]==0.20.1
fi


#=================================================
# SPECIFIC SETUP
#=================================================
# REGISTER SYNAPSE USER AND GET ACCESS TOKEN
#=================================================
ynh_script_progression "Get Synapse access token"

# register $botaccount with $botpassword and get $access_token
#botpassword="$(ynh_string_random --length=30)" #find a way to generate a password
#ynh_app_setting_set --app="$app" --key=botpassword --value="$botpassword"
#access_token=$botpassword

# https://element-hq.github.io/synapse/latest/admin_api/register_api.html

# > GET /_synapse/admin/v1/register

# < {"nonce": "thisisanonce"}

# # Update these values and then paste this code block into a bash terminal
# nonce='thisisanonce'
# username='pepper_roni'
# password='pizza'
# admin='admin'
# secret='shared_secret'

# printf '%s\0%s\0%s\0%s' "$nonce" "$username" "$password" "$admin" |
#   openssl sha1 -hmac "$secret" |
#   awk '{print $2}'

# nonce=$(curl '{"type":"m.login.password", "user":"'$botaccount'", "password":"'$botpassword'"}' "http://localhost:$port_synapse_tls/_synapse/admin/v1/register")

# printf "$botaccount\n$botpassword\n$botpassword\nn" | 
#sudo -u $homeserver $synapse_install_dir/venv/bin/register_new_matrix_user -u $botaccount -p $botpassword -a -c /etc/matrix-$homeserver/homeserver.yaml  || ynh_die "register_new_matrix_user in Synapse failed"
if ! ynh_in_ci_tests; then
	access_token=$(curl '{"type":"m.login.password", "user":"'$botaccount'", "password":"'$botpassword'"}' "http://localhost:$port_synapse_tls/_matrix/client/v3/login")
else
	access_token=$botpassword
fi
ynh_app_setting_set --app="$app" --key=access_token --value="$access_token"

#Prompt to answer 
#New user localpart: $botaccount
#Password: $botpassword
#Confirm password: $botpassword
#Make admin [no]:
#Success!

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

set_bridge_config_from_ids
ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

# This calls allows to set multiple users during install question "botusers" specifying them separated by a comma
#set__listuser
#set__listadmin

chown -R "$app:$app" "$install_dir"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "/var/log/$app/$app.log" $app/$app

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="$app daemon for bridging Matrix messages with a shared WhatsApp&Signal&Co account" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
if ! ynh_in_ci_tests; then
	ynh_systemctl --service="$app" --action="start"
else
	printf "$botpassword\n" | ynh_systemctl --service="$app" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
