#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

#=================================================
# CLEANUP HOMESERVER 
#=================================================
ynh_script_progression "Cleaning up leftovers in homeserver..."

synapse_install_dir=$(ynh_app_setting_get --app $synapse_instance --key install_dir)
synapse_db_name="$(get_synapse_db_name $synapse_instance)"
bot_synapse_db_user="@""$botname"":""$server_name"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
