#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# SPECIFIC REMOVE
#=================================================
# CLEANUP HOMESERVER 
#=================================================
ynh_script_progression "Cleaning up leftovers in homeserver..."

synapse_install_dir=$(ynh_app_setting_get --app $synapse_instance --key install_dir)
synapse_db_name="$(get_synapse_db_name $synapse_instance)"
bot_synapse_db_user="@""$botname"":""$server_name"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
